# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftAssignment' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   
  # Pods for SwiftAssignment
  pod 'ReachabilitySwift'
  pod 'RealmSwift', '~>10'

end
